\set APP_DB_USER 'app'
\set APP_DB_NAME 'app_db'

CREATE USER :APP_DB_USER WITH PASSWORD 'password';
CREATE DATABASE :APP_DB_NAME;
GRANT ALL PRIVILEGES ON DATABASE :APP_DB_NAME TO :APP_DB_USER;
ALTER DATABASE :APP_DB_NAME OWNER TO :APP_DB_USER;

\connect :APP_DB_NAME :APP_DB_USER
BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  password VARCHAR(255) NOT NULL,
  displayName VARCHAR(255) UNIQUE NOT NULL
);

COMMIT;
